# Generated by Django 4.2.4 on 2023-08-21 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(default='to-do', max_length=100),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(default='to-do', max_length=100),
        ),
    ]
